name: hilife
description: A Flutter application to help users far and wide to find and gain easy access to healthcare professionals for all their healthcare enquiries and consultation.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_database: ^3.1.5
  provider: ^4.0.5+1
  shared_preferences: ^0.5.7
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+4
  image_cropper: ^1.2.2
  intl: ^0.16.1
  fluttertoast: ^4.0.1
  cached_network_image: ^2.2.0+1
  photo_view: ^0.9.2
  google_maps_flutter: ^0.5.28+1
  location: ^3.0.2
  flutter_datetime_picker: ^1.3.8
  flutter_material_color_picker: ^1.0.5
  flutter_keyboard_visibility: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
