import 'package:flutter/material.dart';

class Item {
  final int index;
  final String specialisationProfession;
  const Item(this.index, this.specialisationProfession);
}

const List<Item> kProfessions = [
  const Item(0, 'Ambulatory Nurse'),
  const Item(1, 'Anesthesiologist'),
  const Item(2, 'Audiologist'),
  const Item(3, 'Behavioral Health Charge Nurse'),
  const Item(4, 'Bereavement Counselor'),
  const Item(5, 'Cardiac Catheterization Lab Nurse'),
  const Item(6, 'Cardiovascular Operating Room Nurse'),
  const Item(7, 'Cardiovascular Technologist'),
  const Item(8, 'Charge Nurse'),
  const Item(9, 'Chiropractor'),
  const Item(10, 'Counselor'),
  const Item(11, 'Dentist'),
  const Item(12, 'Dermatology Nurse'),
  const Item(13, 'Dialysis Nurse'),
  const Item(14, 'Doctor'),
  const Item(15, 'Emergency Room Nurse'),
  const Item(16, 'Endoscopy Nurse'),
  const Item(17, 'Family Nurse Practitioner'),
  const Item(18, 'Flight Nurse'),
  const Item(19, 'Genetic Counselor'),
  const Item(20, 'Home Health Nurse'),
  const Item(21, 'Hospice Counselor'),
  const Item(22, 'Hospice Nurse'),
  const Item(23, 'House Supervisor Nurse'),
  const Item(24, 'Intensive Care Nurse'),
  const Item(25, 'Interventional Radiology Nurse'),
  const Item(26, 'Labor and Delivery Nurse'),
  const Item(27, 'Lead Registered Nurse'),
  const Item(28, 'Legal Nurse Consultant'),
  const Item(29, 'Licensed Practical Nurse'),
  const Item(30, 'Licensed Vocational Nurse'),
  const Item(31, 'Medical Surgery Nurse'),
  const Item(32, 'Microbiologist'),
  const Item(33, 'Neonatal Intensive Care Nurse'),
  const Item(34, 'Nurse'),
  const Item(35, 'Nurse Anesthetist'),
  const Item(36, 'Nurse Midwife'),
  const Item(37, 'Nurse Practitioner'),
  const Item(38, 'Nursing Assistant'),
  const Item(39, 'Occupational Health Nurse'),
  const Item(40, 'Occupational Health and Safety Specialist'),
  const Item(41, 'Occupational Therapist'),
  const Item(42, 'Office Nurse'),
  const Item(43, 'Oncology Nurse'),
  const Item(44, 'Operating Room Nurse'),
  const Item(45, 'Optician'),
  const Item(46, 'Optometrist'),
  const Item(47, 'Orthodontist'),
  const Item(48, 'Orthotist'),
  const Item(49, 'Outreach RN'),
  const Item(50, 'Paramedic'),
  const Item(51, 'Pediatrician'),
  const Item(52, 'Pediatric Endocrinology Nurse'),
  const Item(53, 'Pediatric Intensive Care Nurse'),
  const Item(54, 'Pediatric Nurse'),
  const Item(55, 'Pediatric Nurse Practitioner'),
  const Item(56, 'Perioperative Nurse'),
  const Item(57, 'Pharmacist'),
  const Item(58, 'Prosthetist'),
  const Item(59, 'Physician'),
  const Item(60, 'Podiatrist'),
  const Item(61, 'Post Anesthesia Nurse'),
  const Item(62, 'Postpartum Nurse'),
  const Item(63, 'Progressive Care Nurse'),
  const Item(64, 'Psychiatric Nurse'),
  const Item(65, 'Psychiatric Nurse Practitioner'),
  const Item(66, 'Public Health Nurse'),
  const Item(67, 'Registered Nurse (RN)'),
  const Item(68, 'Registered Nurse (RN) Case Manager'),
  const Item(69, 'Registered Nurse(RN) Data Coordinator'),
  const Item(70, 'Registered Nurse (RN) First Assistant'),
  const Item(71, 'Registered Nurse (RN) Geriatric Care'),
  const Item(72, 'Registered Nurse (RN) Medical Inpatient Services'),
  const Item(73, 'Registered Nurse (RN) Patient Call Center'),
  const Item(74, 'Registered Nurse (RN) Student Health Services'),
  const Item(75, 'Registered Nurse (RN) Telephone Triage'),
  const Item(76, 'Registered Nurse (RN) Urgent Care'),
  const Item(77, 'Registered Nurse (RN) Women\'s Services'),
  const Item(78, 'Restorative Nurse'),
  const Item(79, 'Registered Medical Assistant'),
  const Item(80, 'Respiration (Inhalation) Therapist'),
  const Item(81, 'School Nurse'),
  const Item(82, 'Speech-Language Pathologist'),
  const Item(83, 'Surgeon'),
  const Item(84, 'Telemetry Nurse'),
  const Item(85, 'Therapist'),
  const Item(86, 'Veterinarian'),
  const Item(87, 'Veterinary Assistant'),
  const Item(88, 'Veterinary Technologist'),
  const Item(89, 'Wellness Nurse'),
];

const List<Item> kSpecialisations = [
  const Item(0, 'Non-Specialist'),
  const Item(1, 'Addiction psychiatrist'),
  const Item(2, 'Adolescent medicine specialist'),
  const Item(3, 'Allergist (immunologist)'),
  const Item(4, 'Anesthesiologist'),
  const Item(5, 'Cardiac electrophysiologist'),
  const Item(6, 'Cardiologist'),
  const Item(7, 'Cardiovascular surgeon'),
  const Item(8, 'Colon and rectal surgeon'),
  const Item(9, 'Critical care medicine specialist'),
  const Item(10, 'Dermatologist'),
  const Item(11, 'Developmental pediatrician'),
  const Item(12, 'Emergency medicine specialist'),
  const Item(13, 'Endocrinologist'),
  const Item(14, 'Family medicine physician'),
  const Item(15, 'Forensic pathologist'),
  const Item(16, 'Gastroenterologist'),
  const Item(17, 'Geriatric medicine specialist'),
  const Item(18, 'Gynecologist'),
  const Item(19, 'Gynecologic oncologist'),
  const Item(20, 'Hand surgeon'),
  const Item(21, 'Hematologist'),
  const Item(22, 'Hepatologist'),
  const Item(23, 'Hospitalist'),
  const Item(24, 'Hospice and palliative medicine specialist'),
  const Item(25, 'Hyperbaric physician'),
  const Item(26, 'Infectious disease specialist'),
  const Item(27, 'Internist'),
  const Item(28, 'Interventional cardiologist'),
  const Item(29, 'Medical examiner'),
  const Item(30, 'Medical geneticist'),
  const Item(31, 'Neonatologist'),
  const Item(32, 'Nephrologist'),
  const Item(33, 'Neurological surgeon'),
  const Item(34, 'Neurologist'),
  const Item(35, 'Nuclear medicine specialist'),
  const Item(36, 'Obstetrician'),
  const Item(37, 'Occupational medicine specialist'),
  const Item(38, 'Oncologist'),
  const Item(39, 'Ophthalmologist'),
  const Item(40, 'Oral surgeon (maxillofacial surgeon)'),
  const Item(41, 'Orthopedic surgeon'),
  const Item(42, 'Otolaryngologist (ear, nose, and throat specialist)'),
  const Item(43, 'Pain management specialist'),
  const Item(44, 'Pathologist'),
  const Item(45, 'Pediatrician'),
  const Item(46, 'Perinatologist'),
  const Item(47, 'Physiatrist'),
  const Item(48, 'Plastic surgeon'),
  const Item(49, 'Psychiatrist'),
  const Item(50, 'Pulmonologist'),
  const Item(51, 'Radiation oncologist'),
  const Item(52, 'Radiologist'),
  const Item(53, 'Reproductive endocrinologist'),
  const Item(54, 'Rheumatologist'),
  const Item(55, 'Sleep disorders specialist'),
  const Item(56, 'Spinal cord injury specialist'),
  const Item(57, 'Sports medicine specialist'),
  const Item(58, 'Surgeon'),
  const Item(59, 'Thoracic surgeon'),
  const Item(60, 'Urologist'),
  const Item(61, 'Vascular surgeon'),
];

final themeColor = Color(0xfff5a623);
final primaryColor = Color(0xff203152);
final greyColor = Color(0xffaeaeae);
final greyColor2 = Color(0xffE8E8E8);

const kInputTextFormFieldLabelColor = TextStyle(color: Colors.black54);
const kTextFieldDecoration = InputDecoration(
  hintText: 'Type a message...',
  contentPadding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
  border: OutlineInputBorder(
    borderRadius: BorderRadius.all(Radius.circular(32.0)),
  ),
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Color(0xff203152), width: 1.0),
    borderRadius: BorderRadius.all(Radius.circular(32.0)),
  ),
  focusedBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Color(0xff203152), width: 2.0),
    borderRadius: BorderRadius.all(Radius.circular(32.0)),
  ),
  hintStyle: TextStyle(color: Colors.grey),
);
const kClientBottomBarTextStyle = TextStyle(fontFamily: 'Piedra', fontSize: 10);

//const List<String> kSpecialist = [
//  'Addiction psychiatrist',
//  'Adolescent medicine specialist',
//  'Allergist (immunologist)',
//  'Anesthesiologist',
//  'Cardiac electrophysiologist',
//  'Cardiologist',
//  'Cardiovascular surgeon',
//  'Colon and rectal surgeon',
//  'Critical care medicine specialist',
//  'Dermatologist',
//  'Developmental pediatrician',
//  'Emergency medicine specialist',
//  'Endocrinologist',
//  'Family medicine physician',
//  'Forensic pathologist',
//  'Gastroenterologist',
//  'Geriatric medicine specialist',
//  'Gynecologist',
//  'Gynecologic oncologist',
//  'Hand surgeon',
//  'Hematologist',
//  'Hepatologist',
//  'Hospitalist',
//  'Hospice and palliative medicine specialist',
//  'Hyperbaric physician',
//  'Infectious disease specialist',
//  'Internist',
//  'Interventional cardiologist',
//  'Medical examiner',
//  'Medical geneticist',
//  'Neonatologist',
//  'Nephrologist',
//  'Neurological surgeon',
//  'Neurologist',
//  'Nuclear medicine specialist',
//  'Obstetrician',
//  'Occupational medicine specialist',
//  'Oncologist',
//  'Ophthalmologist',
//  'Oral surgeon (maxillofacial surgeon)',
//  'Orthopedic surgeon',
//  'Otolaryngologist (ear, nose, and throat specialist)',
//  'Pain management specialist',
//  'Pathologist',
//  'Pediatrician',
//  'Perinatologist',
//  'Physiatrist',
//  'Plastic surgeon',
//  'Psychiatrist',
//  'Pulmonologist',
//  'Radiation oncologist',
//  'Radiologist',
//  'Reproductive endocrinologist',
//  'Rheumatologist',
//  'Sleep disorders specialist',
//  'Spinal cord injury specialist',
//  'Sports medicine specialist',
//  'Surgeon',
//  'Thoracic surgeon',
//  'Urologist',
//  'Vascular surgeon',
//];

//const List<String> kProfessions = [
//  'Ambulatory Nurse',
//  'Anesthesiologist',
//  'Audiologist',
//  'Behavioral Health Charge Nurse',
//  'Bereavement Counselor',
//  'Cardiac Catheterization Lab Nurse',
//  'Cardiovascular Operating Room Nurse',
//  'Cardiovascular Technologist',
//  'Charge Nurse',
//  'Chiropractor',
//  'Counselor',
//  'Dentist',
//  'Dermatology Nurse',
//  'Dialysis Nurse',
//  'Doctor',
//  'Emergency Room Nurse',
//  'Endoscopy Nurse',
//  'Family Nurse Practitioner',
//  'Flight Nurse',
//  'Genetic Counselor',
//  'Home Health Nurse',
//  'Hospice Counselor',
//  'Hospice Nurse',
//  'House Supervisor Nurse',
//  'Intensive Care Nurse',
//  'Interventional Radiology Nurse',
//  'Labor and Delivery Nurse',
//  'Lead Registered Nurse',
//  'Legal Nurse Consultant',
//  'Licensed Practical Nurse',
//  'Licensed Vocational Nurse',
//  'Medical Surgery Nurse',
//  'Microbiologist',
//  'Neonatal Intensive Care Nurse',
//  'Nurse',
//  'Nurse Anesthetist',
//  'Nurse Midwife',
//  'Nurse Practitioner',
//  'Nursing Assistant',
//  'Occupational Health Nurse',
//  'Occupational Health and Safety Specialist',
//  'Occupational Therapist',
//  'Office Nurse',
//  'Oncology Nurse',
//  'Operating Room Nurse',
//  'Optician',
//  'Optometrist',
//  'Orthodontist',
//  'Orthotist',
//  'Outreach RN',
//  'Paramedic',
//  'Pediatrician',
//  'Pediatric Endocrinology Nurse',
//  'Pediatric Intensive Care Nurse',
//  'Pediatric Nurse',
//  'Pediatric Nurse Practitioner',
//  'Perioperative Nurse',
//  'Pharmacist',
//  'Prosthetist',
//  'Physician',
//  'Podiatrist',
//  'Post Anesthesia Nurse',
//  'Postpartum Nurse',
//  'Progressive Care Nurse',
//  'Psychiatric Nurse',
//  'Psychiatric Nurse Practitioner',
//  'Public Health Nurse',
//  'Registered Nurse (RN)',
//  'Registered Nurse (RN) Case Manager',
//  'Registered Nurse(RN) Data Coordinator',
//  'Registered Nurse (RN) First Assistant',
//  'Registered Nurse (RN) Geriatric Care',
//  'Registered Nurse (RN) Medical Inpatient Services',
//  'Registered Nurse (RN) Patient Call Center',
//  'Registered Nurse (RN) Student Health Services',
//  'Registered Nurse (RN) Telephone Triage',
//  'Registered Nurse (RN) Urgent Care',
//  'Registered Nurse (RN) Women\'s Services',
//  'Restorative Nurse',
//  'Registered Medical Assistant',
//  'Respiration (Inhalation) Therapist',
//  'School Nurse',
//  'Speech-Language Pathologist',
//  'Surgeon',
//  'Telemetry Nurse',
//  'Therapist',
//  'Veterinarian',
//  'Veterinary Assistant',
//  'Veterinary Technologist',
//  'Wellness Nurse',
//];
