import 'package:flutter/material.dart';

final themeColor = Color(0xfff5a623);
final primaryColor = Color(0xff203152);
final greyColor = Color(0xffaeaeae);
final greyColor2 = Color(0xffE8E8E8);

const kInputTextFormFieldLabelColor = TextStyle(color: Colors.black54);
const kTextFieldDecoration = InputDecoration(
  hintText: 'Type a message...',
  contentPadding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 20.0),
  border: OutlineInputBorder(
    borderRadius: BorderRadius.all(Radius.circular(32.0)),
  ),
  enabledBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Color(0xff203152), width: 1.0),
    borderRadius: BorderRadius.all(Radius.circular(32.0)),
  ),
  focusedBorder: OutlineInputBorder(
    borderSide: BorderSide(color: Color(0xff203152), width: 2.0),
    borderRadius: BorderRadius.all(Radius.circular(32.0)),
  ),
  hintStyle: TextStyle(color: Colors.grey),
);

const List<String> kSpecialist = [
  'Addiction psychiatrist',
  'Adolescent medicine specialist',
  'Allergist (immunologist)',
  'Anesthesiologist',
  'Cardiac electrophysiologist',
  'Cardiologist',
  'Cardiovascular surgeon',
  'Colon and rectal surgeon',
  'Critical care medicine specialist',
  'Dermatologist',
  'Developmental pediatrician',
  'Emergency medicine specialist',
  'Endocrinologist',
  'Family medicine physician',
  'Forensic pathologist',
  'Gastroenterologist',
  'Geriatric medicine specialist',
  'Gynecologist',
  'Gynecologic oncologist',
  'Hand surgeon',
  'Hematologist',
  'Hepatologist',
  'Hospitalist',
  'Hospice and palliative medicine specialist',
  'Hyperbaric physician',
  'Infectious disease specialist',
  'Internist',
  'Interventional cardiologist',
  'Medical examiner',
  'Medical geneticist',
  'Neonatologist',
  'Nephrologist',
  'Neurological surgeon',
  'Neurologist',
  'Nuclear medicine specialist',
  'Obstetrician',
  'Occupational medicine specialist',
  'Oncologist',
  'Ophthalmologist',
  'Oral surgeon (maxillofacial surgeon)',
  'Orthopedic surgeon',
  'Otolaryngologist (ear, nose, and throat specialist)',
  'Pain management specialist',
  'Pathologist',
  'Pediatrician',
  'Perinatologist',
  'Physiatrist',
  'Plastic surgeon',
  'Psychiatrist',
  'Pulmonologist',
  'Radiation oncologist',
  'Radiologist',
  'Reproductive endocrinologist',
  'Rheumatologist',
  'Sleep disorders specialist',
  'Spinal cord injury specialist',
  'Sports medicine specialist',
  'Surgeon',
  'Thoracic surgeon',
  'Urologist',
  'Vascular surgeon',
];

const List<String> kProfessions = [
  'Ambulatory Nurse',
  'Anesthesiologist',
  'Audiologist',
  'Behavioral Health Charge Nurse',
  'Bereavement Counselor',
  'Cardiac Catheterization Lab Nurse',
  'Cardiovascular Operating Room Nurse',
  'Cardiovascular Technologist',
  'Charge Nurse',
  'Chiropractor',
  'Counselor',
  'Dentist',
  'Dermatology Nurse',
  'Dialysis Nurse',
  'Doctor',
  'Emergency Room Nurse',
  'Endoscopy Nurse',
  'Family Nurse Practitioner',
  'Flight Nurse',
  'Genetic Counselor',
  'Home Health Nurse',
  'Hospice Counselor',
  'Hospice Nurse',
  'House Supervisor Nurse',
  'Intensive Care Nurse',
  'Interventional Radiology Nurse',
  'Labor and Delivery Nurse',
  'Lead Registered Nurse',
  'Legal Nurse Consultant',
  'Licensed Practical Nurse',
  'Licensed Vocational Nurse',
  'Medical Surgery Nurse',
  'Microbiologist',
  'Neonatal Intensive Care Nurse',
  'Nurse',
  'Nurse Anesthetist',
  'Nurse Midwife',
  'Nurse Practitioner',
  'Nursing Assistant',
  'Occupational Health Nurse',
  'Occupational Health and Safety Specialist',
  'Occupational Therapist',
  'Office Nurse',
  'Oncology Nurse',
  'Operating Room Nurse',
  'Optician',
  'Optometrist',
  'Orthodontist',
  'Orthotist',
  'Outreach RN',
  'Paramedic',
  'Pediatrician',
  'Pediatric Endocrinology Nurse',
  'Pediatric Intensive Care Nurse',
  'Pediatric Nurse',
  'Pediatric Nurse Practitioner',
  'Perioperative Nurse',
  'Pharmacist',
  'Prosthetist',
  'Physician',
  'Podiatrist',
  'Post Anesthesia Nurse',
  'Postpartum Nurse',
  'Progressive Care Nurse',
  'Psychiatric Nurse',
  'Psychiatric Nurse Practitioner',
  'Public Health Nurse',
  'Registered Nurse (RN)',
  'Registered Nurse (RN) Case Manager',
  'Registered Nurse(RN) Data Coordinator',
  'Registered Nurse (RN) First Assistant',
  'Registered Nurse (RN) Geriatric Care',
  'Registered Nurse (RN) Medical Inpatient Services',
  'Registered Nurse (RN) Patient Call Center',
  'Registered Nurse (RN) Student Health Services',
  'Registered Nurse (RN) Telephone Triage',
  'Registered Nurse (RN) Urgent Care',
  'Registered Nurse (RN) Women\'s Services',
  'Restorative Nurse',
  'Registered Medical Assistant',
  'Respiration (Inhalation) Therapist',
  'School Nurse',
  'Speech-Language Pathologist',
  'Surgeon',
  'Telemetry Nurse',
  'Therapist',
  'Veterinarian',
  'Veterinary Assistant',
  'Veterinary Technologist',
  'Wellness Nurse',
];
